name: My EKS Workflow

on:
  push:
    branches:
      - main  # Update branch name if needed

jobs:
  build-and-deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install AWS CLI (optional, adjust based on your setup)
        run: |
          sudo apt-get update
          sudo apt-get install -y awscli jq  # Install jq if needed for parsing outputs

      - name: Configure AWS credentials (assuming pre-configured access)
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws configure set region ${{ secrets.AWS_REGION }}

      - name: Update kubeconfig with EKS credentials
        run: aws eks update-kubeconfig --name harisheks --region ap-south-1 --kubeconfig ~/.kube/config

      - name: Build and Deploy (uses shared script)
        run: ./scripts/build_deploy.sh "${{ secrets.CLUSTER_NAME }}" "${{ secrets.REGION }}" "${{ secrets.NAMESPACE }}" ".github/workflows/deployment.yml"
