name: Deploy Pods and Services to EKS

on:
  push:
    branches:
      - main

env:
  AWS_REGION: ap-south-1 # Replace with your AWS region
  CLUSTER_NAME: harisheks  # Replace with your EKS cluster name
  NAMESPACE: my-namespace  # Replace with your namespace

jobs:
  deploy:
    name: Deploy Pod and Service
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: SSH into bastion host and deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          script: |
            scp -i ${{ secrets.SERVER_SSH_KEY }} deployment.yml ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_HOST }}:/root
            pwd 
            ls
            aws eks update-kubeconfig --name ${{ env.CLUSTER_NAME }} --region ${{ env.AWS_REGION }} --kubeconfig ~/.kube/config
            kubectl apply -f deployment.yml -n ${{ env.NAMESPACE }}
      - name: Apply deployment.yml
        run: kubectl apply -f deployment.yml -n ${{ env.NAMESPACE }}
